### ISSUE TITLE
AC-17(1): monitor+control remote access methods (relate to AC-2 on how monitoring remote access is equivalent to monitoring ANY access)

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#17]

**Comment by shawndwells** [comment]
added comment that auditing captures local+remote events equally

**Comment by enham** [comment]
Delegated to the infrastructure provider. SSH is required for OpenShift for installation and maintenance. SSH must be configured to block access except from well-known access points/whitelist that is outside the OpenShift cluster such as a jump box; password-based authentication must be disabled.
