### ISSUE TITLE
AU-7: open shift must support on-demand audit review. document where logs can be found.

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#27]

**Comment by shawndwells** [comment]
OpenShift embeds the Elasticsearch, Fluentd, and Kibana (EFK) stack. This pre-integrated audit reduction capability aggregates logs from nodes and applications running inside your OpenShift Container Platform installation. Once deployed it uses Fluentd to aggregate event logs from all notes, projects, and pods into Elasticsearch (ES). It also provides a centralized Kibana web UI where users and administrators can create rich visualizations and dashboards with the aggregated data. Triggers may be setup to detect atypical use.

For aggregate log sizing information, refer to the “Aggregate Logging Sizing Guidelines” of the Installation and Configuration guide: https://docs.openshift.com/container-platform/3.3/install_config/aggregate_logging_sizing.html

For instructions on how to configure aggregate logging, refer to the “Aggregating Container Logs” section of the Installation and Configuration guide: https://docs.openshift.com/container-platform/3.3/install_config/aggregate_logging.html

**Comment by shawndwells** [comment]
![image](https://cloud.githubusercontent.com/assets/5713754/19461223/c44aea4c-94b0-11e6-92a3-44c3784eb584.png)

**Comment by enham** [comment]
Additionally, auditing events from OpenShift can be configured to leverage the underlying Audit Subsystem of RHEL. https://docs.openshift.com/container-platform/3.3/install_config/master_node_configuration.html#master-node-config-audit-config

**Comment by enham** [comment]
OpenShift does not provide reporting on top of audit logs. This is a concern outside of OpenShift.
