### ISSUE TITLE
AU-8: audit must use internal clocks to generate time stamps. records must be mapped to UTC or GMT

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#28]

**Comment by enham** [comment]
This control implementation is typically delegated to the infrastructure provider for configuration of the underlying RHEL operating system for OpenShift so that the NTP service relies on NIST provided time sources.

However, OpenShift audit logs must be configured.

**Comment by bit4man** [comment]
https://docs.openshift.com/container-platform/3.3/install_config/master_node_configuration.html#master-node-config-audit-config

**Comment by shawndwells** [comment]
![image](https://cloud.githubusercontent.com/assets/5713754/20545374/dfe10870-b0dc-11e6-956a-8c06bd120005.png)
