### ISSUE TITLE
AC-2(3): Disable inactive accounts after 90 days

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#3]

**Comment by shawndwells** [comment]
OpenShift does not have the capability to automatically disable accounts after a configured period of time. To meet this requirement, an authentication provider (such as Active Directory) must be used. Integration between OpenShift and Active Directory can be accomplished through the use of Kerberos cross-realm trusts. Refer to the “LDAP Authentication” section of the OpenShift Administrators guide: https://docs.openshift.com/container-platform/3.3/admin_solutions/authentication.html#ldap-auth>

**Comment by enham** [comment]
This is a feature of the authentication provider.
