### ISSUE TITLE
AU-8(1)r1: must use primary and secondary time servers used by NIST time service. 2nd must be from geographically different location than primary

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#30]

**Comment by shawndwells** [comment]
Procedural control. Nothing to do with OpenShift.

**Comment by enham** [comment]
This control implementation is typically delegated to the infrastructure provider for configuration of the underlying RHEL operating system for OpenShift so that the NTP service relies on NIST provided time sources.
