### ISSUE TITLE
CM-5(3): verify s/w components have been digitally signed using a certificate that is recognized and approved by the organization (both of OpenShift core + containers)

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#34]

**Comment by enham** [comment]
Yes Red Hat digitally signs our software, please see:  https://access.redhat.com/security/team/key

In order for us to implement this control, OpenShift must be installed using Red Hat Subscription Manager (rpm-based install with GPG enabled). All containers downloaded from Red Hat's container registry (registry.redhat.com) must have the SHA hash validated.

We delegate the container signing to the tenant.

**Comment by shawndwells** [comment]
@enham current text has the yum gpg checks enabled. Is there a way to force SHA validation of container images upon download?

**Comment by enham** [comment]
No, you have to do it manually.

**Comment by shawndwells** [comment]
@enham - What specific commands or GUI processes need to be followed for verifying SHA's of container images?
