### ISSUE TITLE
CM-6 (1): The organization employs automated mechanisms to centrally manage, apply, and verify configuration settings

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#35]

**Comment by aclater** [comment]
@shawndwells as mentioned - this is solved via Ansible, which I know OSE uses as its installer - not sure if it is used ongoing for upgrade, etc.  Could pull from EPEL to satisfy.

**Comment by shawndwells** [comment]
thanks @aclater. Added the following:

 <The customer will be responsible for employing automated mechanisms to centrally manage, apply, and verify configuration settings for information system components. A successful control response will describe any automated systems in place used to manage, apply, and verify configuration settings. An example of this would be the use of Red Hat Satellite, Red Hat Ansible, or a combination of both.>

**Comment by enham** [comment]
Ansible is used for upgrades and maintenance as well. A lot of this will fall under the domain of the infrastructure provider to create and maintain playbooks. Satellite has a role here as well.

**Comment by shawndwells** [comment]
![image](https://cloud.githubusercontent.com/assets/5713754/20545095/2e193078-b0db-11e6-8624-4ec3a6f7d24e.png)
