### ISSUE TITLE
CM-7 (2): The information system prevents program execution  (can openshift blacklist apps? or punt to trusted registry workflow?)

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#36]

**Comment by enham** [comment]
OpenShift allows for configurable registry access so an organization could limit the images available to an end user. For example, an OpenShift deployment architecture could include segmentation for different environments (i.e. DEV, TEST, PROD) and increasing level of privilege required to promote application images and execute those applications in higher environments.

**Comment by shawndwells** [comment]
@enham - Sounds spot on! How is this access configured?
