### ISSUE TITLE
AC-2(4): Audit user creation/mods/enable/disable/removal, auto notifies admin on these events

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#4]

**Comment by shawndwells** [comment]
OpenShift will log events to standardized files, however automatic notification (outside of generating audit data) is not possible. As an OpenShift Container Platform cluster administrator, you can deploy the EFK stack to aggregate logs for a range of OpenShift Container Platform services and setup alerting. Application developers can view the logs of the projects for which they have view access. The EFK stack aggregates logs from hosts and applications, whether coming from multiple containers or even deleted pods. For documentation on how to setup Elasticsearch, Fluentd, and Kibana, refer to the “Aggregate Logging” section of the OpenShift Installation and Configuration Guide: https://docs.openshift.com/container-platform/3.3/install_config/aggregate_logging.html

**Comment by enham** [comment]
Delegated to infrastructure provider. But this could be accomplished with CloudForms...
