### ISSUE TITLE
IA-2: The information system uniquely identifies and authenticates organizational users (or processes acting on behalf of organizational users).

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#42]

**Comment by shawndwells** [comment]
defer to AD integration:

 As an OpenShift Container Platform administrator, you can use groups to manage users, change their permissions, and enhance collaboration. Your organization may have already created user groups and stored them in an LDAP server, such as Active Directory. OpenShift Container Platform can sync those LDAP records with internal OpenShift Container Platform records, enabling you to manage your groups in one place. OpenShift Container Platform currently supports group sync with LDAP servers using three common schemas for defining group membership: RFC 2307, Active Directory, and augmented Active Directory. For additional information, refer to “Syncing Groups with LDAP” in the OpenShift Installation and Configuration guide: https://docs.openshift.com/container-platform/3.3/install_config/syncing_groups_with_ldap.html

**Comment by enham** [comment]
OpenShift usernames can be mapped to multiple identities from different providers, although it will not allow you to login and authenticate against multiple systems at once. System administrator access is required to accomplish this and access should be limited.
