### ISSUE TITLE
IA-2 (1) The information system implements multifactor authentication for network access to privileged accounts.

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#45]

**Comment by shawndwells** [comment]
Doesn't appear OpenShift supports multi-factor auth:

https://docs.openshift.com/container-platform/3.3/admin_solutions/authentication.html

**Comment by michaelepley** [comment]
Openshift provides a pluggable authentication architecture that can utilize 3rd party authentication schemes that include multifactor authentication. The authentication subsystem in openshift relies on OAuth 2.0 and any system that can interact with the OAuth token service over HTTPS can receive authentication tokens. Typically this is implemented using Openshift's provided RequestHeaderIdentityProvider as described in section 12.3.8. Request Header of the Openshift 3.3 Installation and Configuration Guide.

**Comment by shawndwells** [comment]
![image](https://cloud.githubusercontent.com/assets/5713754/20546016/ac934baa-b0e0-11e6-8011-d1fef076235e.png)
