### ISSUE TITLE
SI-10: The information system checks the validity of [Assignment: organization-defined information inputs].

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#49]

**Comment by enham** [comment]
Let's discuss offline... but out of the box, we don't satisfy.

**Comment by shawndwells** [comment]
The "organization-defined information inputs" are defined as:

![image](https://cloud.githubusercontent.com/assets/5713754/20545016/c368222a-b0da-11e6-957a-fe275378c7b4.png)
