### ISSUE TITLE
AC-2(5): Auto logout after time period (e.g. 15min)

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#5]

**Comment by shawndwells** [comment]
```
# grep -rin sessionMaxAgeSeconds

master/master-config.yaml:175:    sessionMaxAgeSeconds: 300
```

ref: /var/lib/origin/openshift.local.config

**Comment by shawndwells** [comment]
Hayyyyy @aclater, think you could dig up how to configure this in OpenShift enterprise?

**Comment by shawndwells** [comment]
Or actually, @jason-callaway, did you guys configure this for the C2S deployment?

**Comment by michaelepley** [comment]
sessionMaxAgeSeconds is only the the token retrieval process; accessTokenMaxAgeSeconds controls how long a token is valid for and the one you probably want.

**Comment by enham** [comment]
Also related to AC-11(1)
