### ISSUE TITLE
SC-7(c) Connects to external networks or information systems only through managed interfaces consisting of boundary protection devices arranged in accordance with organizational security architecture

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#60]

**Comment by enham** [comment]
Delegated to infrastructure provider.

**Comment by shawndwells** [comment]
@enham is there a way to statically associate openshift services on a particular ethernet device? or IP address?

e.g. in Apache, you can bond to particular network via the ``Listen`` directives:
`````
Listen 192.0.2.1:80
Listen 192.0.2.5:8000
`````

**Comment by michaelepley** [comment]
To meet this control, Openshift must be deployed as a containerized deployment is accordance with 2.4. Containerized Components of the Openshift 3.3 Installation and Configuration guide. Openshift controls network resources through the use of OpenVSwitch (OVS) and the docker daemon runtime configuration. The standard OVS configuration creates a number of virtual network bridges and devices to connect openshift nodes in one or more virtual networks. When Openshift is deployed as a containerized deployment, it is running completely on the docker runtime and its network is managed by docker's networking. The docker networking must be configured to allow access to the desired, restricted set of physical networking resources. Openshift will then deploy containers against the docker networking configuration to connect to the OVS network bridge devices and virtual interfaces.
