### ISSUE TITLE
SC-7(b) Implements subnetworks for publicly accessible system components that are [Selection: physically; logically] separated from internal organizational networks; and

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#61]

**Comment by michaelepley** [comment]
This control is partly satisfied by delegation to the infrastructure provider and partly satisfied by implementation of logical network separation.  Openshift must be deployed as a containerized deployment is accordance with 2.4. Containerized Components of the Openshift 3.3 Installation and Configuration guide. A virtual network layer is created by Openshift's OpenVSwitch (OVS) SDN, connecting all containers deployed by openshift, and isolating and/or controlling access between external systems and organizational networks.
