### ISSUE TITLE
AC-2(12): how can we ship logs to external source (e.g. via rsyslog, or to splunk)

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#7]

**Comment by enham** [comment]
For tenant application logs, this is a shared responsibility between OpenShift and the tenant security control implementation. OpenShift provides centralized log capture and aggregation, provided the tenant logs to stdout or stderr streams. Fluentd captures stdout and stderr and can be configured to forward logs to an external log service (i.e. splunk). The other tenants may also provide fluentd plugins to forward logs from other sources or locations to the external log service (i.e. splunk).

**Comment by enham** [comment]
OpenShift logs are captured by rsyslogd which must also be configured to forward logs to an external log service. Similarly, fluentd could also be configured in this capacity (prefer fluentd for scalability).  **NB: Kubernetes event logs are not captured by the external log service, but only reside in the etcd database. The etcd database must be configured with a fluentd plugin to forward Kubernetes events to the external service.**

**Comment by shawndwells** [comment]
@enham How specifically do we enable those plugins? For example, the level of detail needed from the RHEL guides:

http://people.redhat.com/swells/scap-security-guide/RHEL/7/output/ssg-rhel7-guide-ospp-rhel7-server.html

``
Rsyslog Logs Sent To Remote Hostgroup
If system logs are to be useful in detecting malicious activities, it is necessary to send logs to a remote server. An intruder who has compromised the root account on a machine may delete the log entries which indicate that the system was attacked before they are seen by an administrator. 

However, it is recommended that logs be stored on the local host in addition to being sent to the loghost, especially if rsyslog has been configured to use the UDP protocol to send messages over a network. UDP does not guarantee reliable delivery, and moderately busy sites will lose log messages occasionally, especially in periods of high traffic which may be the result of an attack. In addition, remote rsyslog messages are not authenticated in any way by default, so it is easy for an attacker to introduce spurious messages to the central log server. Also, some problems cause loss of network connectivity, which will prevent the sending of messages to the central server. For all of these reasons, it is better to store log messages both centrally and on each host, so that they can be correlated if necessary.

Ensure Logs Sent To Remote Hostrule

To configure rsyslog to send logs to a remote log server, open /etc/rsyslog.conf and read and understand the last section of the file, which describes the multiple directives necessary to activate remote logging. Along with these other directives, the system can be configured to forward its logs to a particular log server by adding or correcting one of the following lines, substituting loghost.example.com appropriately. The choice of protocol depends on the environment of the system; although TCP and RELP provide more reliable message delivery, they may not be supported in all environments. 
To use UDP for log message delivery:

*.* @loghost.example.com

To use TCP for log message delivery:
*.* @@loghost.example.com

To use RELP for log message delivery:
*.* :omrelp:loghost.example.com

``
