### ISSUE TITLE
IA-7: The system implements mechanisms for authentication to a cryptographic module that meet the requirements of applicable federal laws, Executive Orders, directives, policies, regulations, standards, and guidance for such authentication.

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#75]

**Comment by enham** [comment]
Shawn, can you answer wrt to FIPS?

**Comment by shawndwells** [comment]
Currently have documented how to ensure SSH logins are over FIPS:
![image](https://cloud.githubusercontent.com/assets/5713754/20545277/5176e938-b0dc-11e6-9843-56364c0d527f.png)


Need content on how to FIPS enable any authentication providers -- such as APIs and the console

**Comment by shawndwells** [comment]
e.g. if JBoss or Tomcat is used to serve the console, need to document how to ensure HTTPS is used over TLS
