### ISSUE TITLE
AC-6(9): audit “privileged functions.” What are privileged functions wrt open shift? How to enable custom audit rules for them?

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#8]

**Comment by enham** [comment]
This should be satisfied by standard audit logging.

**Comment by shawndwells** [comment]
@enham here are the high-level events that need to be audited. does OpenShift cover all these by default?

Also, is are any configuration flags needed within OpenShift to audit container start/stop, uploading a container, etc? 

![image](https://cloud.githubusercontent.com/assets/5713754/20544967/9575cf0c-b0da-11e6-840a-ea140c62add9.png)


![image](https://cloud.githubusercontent.com/assets/5713754/20544977/9c646436-b0da-11e6-9113-330df0d7a50b.png)
