### ISSUE TITLE
IA-4 (4) : The organization manages individual identifiers by uniquely identifying each individual as [FedRAMP Assignment: contractors; foreign nationals].

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#85]

**Comment by enham** [comment]
The authentication provider must provide extended attributes so that OpenShift can map groups/roles to them.

**Comment by shawndwells** [comment]
![image](https://cloud.githubusercontent.com/assets/5713754/20545501/8b7a734c-b0dd-11e6-9726-9c30fdb2eb0b.png)
