### ISSUE TITLE
IA-2 (8): The information system implements replay-resistant authentication mechanisms for network access to privileged accounts.

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#89]

**Comment by shawndwells** [comment]
Added language to use Azure AD services

**Comment by rlucente-retro** [comment]
OpenShift must be configured to use SSL/TLS for all internal and external connections.  According to the TLS 1.1 specification Appendix F.2:

> To prevent message replay or modification attacks, the MAC is computed from the MAC secret, the sequence number, the message length, the message contents, and two fixed character strings.

**Comment by shawndwells** [comment]
![image](https://cloud.githubusercontent.com/assets/5713754/20545587/fd669b02-b0dd-11e6-94d1-1936f63f818f.png)
