### ISSUE TITLE
AC-2(9): group authenticators

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#98]

**Comment by shawndwells** [comment]
Added text stating that openshift does not have group authenticators.

**Comment by shawndwells** [comment]
(e.g. shared logins is not a technical feature -- rather something that would be procedural controlled by deployment)

**Comment by michaelepley** [comment]
Openshift provides a role based access control (RBAC) mechanism and user identity metadata including group membership metadata. Identity and RBAC controls are enforced against all user (privileged and non-privileged) actions and resources. RBAC access controls can be applied to provide access to resources by individual users or groups of users. Groups are typically configured in accordance with section 3.4. Managing User and Group Labels in Openshift 3.3's Cluster Administration Guide.

**Comment by shawndwells** [comment]
Updated with @michaelepley 's language:

![image](https://cloud.githubusercontent.com/assets/5713754/20545874/ac4ca7aa-b0df-11e6-8e86-96b686a6d8d9.png)
